// <auto-generated />
using GraniteHouse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace NotDonkeyApp_UG.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190510185402_addedNotDonkeyModel")]
    partial class addedNotDonkeyModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NotDonkeyApp_UG.Models.AnimalNotDonkey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalDescription")
                        .IsRequired()
                        .HasMaxLength(2137);

                    b.Property<string>("AnimalType")
                        .IsRequired();

                    b.Property<string>("AnimalsYouLike");

                    b.Property<bool>("IsDonkey");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int>("OwnerPhoneNumber");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.ToTable("NotDonkeys");
                });
#pragma warning restore 612, 618
        }
    }
}
